SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Pro].[ArchivalEmailAddresses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[EmailAddress] [nchar](255) NOT NULL,
 CONSTRAINT [PK_ArchivalEmailAddresses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Pro].[ArchivalEmailAddresses]  WITH CHECK ADD  CONSTRAINT [FK_ArchivalEmailAddresses_Users] FOREIGN KEY([UserId])
REFERENCES [Pro].[Users] ([Id])
GO

ALTER TABLE [Pro].[ArchivalEmailAddresses] CHECK CONSTRAINT [FK_ArchivalEmailAddresses_Users]
GO